### ISSUE TITLE
How to create an ObjCInstance that is known to adhere to a protocol ?

### ISSUE THREAD

**Issue by sramij-code** [beeware/rubicon-objc#140] opened 2019-10-21 16:28 UTC
I am loading "Metal.framework" and instantiating an object of type (ObjC) `id<MTLDevice> ` (adheres to the MTLDevice protocol).
One property definition of this protocol goes like this:
`@property(readonly) MTLSize maxThreadsPerThreadgroup;`

However, when I try to access it (as a getter, not a setter), the encoding of MTLSize which is unknown to rubicon's runtime comes back as _Anonymous.
```
import os
import sys
from ctypes import *
from rubicon.objc import NSUInteger
from rubicon.objc import types
import rubicon.objc as ru

def main():

    _MTLSizeEncoding = b'{_MTLSize=QQQ}'
    @types.with_preferred_encoding(_MTLSizeEncoding)
    class MTLSize(Structure):
        _fields_ = [
            ("width",  NSUInteger),
            ("height", NSUInteger),
            ("depth",  NSUInteger),
        ]

    metal = ru.runtime.load_library('Metal')
    metal.MTLCreateSystemDefaultDevice.restype = ru.runtime.objc_id
    device = metal.MTLCreateSystemDefaultDevice()
    device = ru.ObjCInstance(device)

    res = device.maxThreadsPerThreadgroup
    print(res)		# <rubicon.objc.types._Anonymous object at 0x1094599d8>
    print(res()) 	         # TypeError: '_Anonymous' object is not callable

Hence, I am not able to access the "MTLSize" values.
if __name__ == '__main__':
    main()
```

I tried so many ways to tell rubicon about this MTLSize type as It my code shows w/o success.
The only thing I was able to get working is this:
```
res = send_message(device, 'maxThreadsPerThreadgroup', restype=MTLSize)    
print(res.width)
```
But I was hopping I won't need to do it and rubicon would infer types automatically here, or I would somehow tell it to load device as an object adhering to the `MTLDevice` protocol, not as `objc_id`.

**Comment by dgelessus** [comment] 2019-10-21 22:10
Your code is almost completely correct, you only need to change the type encoding slightly. The correct encoding for `MTLSize` is `{?=QQQ}`, not `{_MTLSize=QQQ}`. With this change the code works on my Mac (macOS 10.14).

It's not very obvious why the type encoding needs a `?` in it instead of a proper name, so here's a long explanation. (Depending on how well you know C, you might already know most of this.) In C, the basic syntax for defining structs looks like this:

```c
struct structname {
    int foo, bar;
};
```

This defines the type `struct structname`, and the encoding for this type is `{structname=ii}`.

With the `typedef` keyword, you can define a new name for this struct type:

```c
typedef struct structname typename;
```

This defines a type called `typename` that is the same as `struct structname`. (Because `typename` was created using `typedef`, it doesn't have a `struct` prefix like `struct structname` has.) `typename` is identical to `struct structname`, so it has the same type encoding, `{structname=ii}`.

C also allows you to combine the struct definition and the `typedef` into a single statement:

```c
typedef struct structname {
    int foo, bar;
} typename;
```

This does the same thing as the two previous code blocks combined - it defines the struct type `struct structname` and a type `typename` that is identical to the struct type. The encoding of both types is `{structname=ii}`. Note the type encoding uses the `struct` name and not the name from the `typedef`.

With the struct definition and `typedef` combined into one statement, you can also remove the `struct` name and leave only the `typedef` name:

```c
typedef struct {
    int foo, bar;
} typename;
```

This defines a struct without a `struct` name, and then defines a type `typename` that is identical to this struct. The type encoding of this struct is now `{?=ii}`. Like before, the name in the encoding is based on the `struct` name, not the `typedef` name. In this case there is no `struct` name, so instead `?` is used as a replacement.

Now if you look at the definition of `MTLSize`, from `Metal/MTLTypes.h`:

```c
typedef struct {
    NSUInteger width, height, depth;
} MTLSize;
```

you can see that it uses the same form as my last example - an unnamed struct definition inside a `typedef`. Because the name is given by the `typedef` and not by the `struct`, the type encoding is `{?=QQQ}`, not `{MTLSize=QQQ}`.

I hope this explanation makes sense. If you have any more questions, please ask 🙂

**Comment by freakboy3742** [comment] 2019-10-22 00:01
@dgelessus That definitely makes sense why the data structure is coming through as "anonymous"; but why does the Bridgesupport file for Metal (`/System/Library/Frameworks/Metal.framework/Resources/BridgeSupport/Metal.bridgesupport`) define the encoding as `{_MTLSize=QQQ}`? 

The "set an encoding for `?`" trick will only work for one type - if we have more than one ambiguous typedef (which seems more than likely), how can we disambiguate the usage? Is providing an analog of ctypes `method.retval` our only option here?

**Comment by dgelessus** [comment] 2019-10-22 06:43
@freakboy3742 That's interesting. The BridgeSupport file isn't consistent even within itself though, it uses at least three different encodings for `MTLSize`:

* In the `<struct name='MTLSize' .../>` tag near the top, it defines the type as `{_MTLSize="width"Q"height"Q"depth"Q}`. Here the encoding includes a struct name and also the names of the individual fields. I think I've seen this kind of encoding before, but it usually doesn't appear at runtime.
* In the `<function inline='true' name='MTLSizeMake'>...</function>` tag further below, the type encoding `{_MTLSize=QQQ}` is used. This still has a struct name, but no field names.
* Even further below, in `<informal_protocol name='MTLDevice'>...</informal_protocol>`, specifically in the method (actually a property) `maxThreadsPerThreadgroup`, the encoding is `{?=QQQ}`, without a struct name.

I'm not sure where these inconsistencies come from. It's possible that Apple generates these BridgeSupport files from debug builds that include more runtime metadata than the release versions, or perhaps the headers changed at some point and the BridgeSupport data is partially outdated. I'll need to check the headers from some older Xcode versions to confirm that.

And you are correct, there will be conflicts if there are multiple anonymous structs with the same field types. In fact this will already happen within Metal - both `MTLSize` and `MTLOrigin` have the encoding `{?=QQQ}`.

I'm not sure if there is a good solution for this conflict right now - you can either define a single struct type and use it to represent both `MTLSize` and `MTLOrigin`, or you can explicitly set each method's `restype`. The first option is not ideal, because the types are not supposed to be identical, and the field names are different. The second option is not very convenient, because you have to use `send_message` and pass the `restype` on each call. This could be improved though - we could add `restype` and `argtypes` fields to our method objects to allow permanently setting the types, rather than having to pass them on each call.

**Comment by sramij-code** [comment] 2019-10-22 09:12
@dgelessus The anonymous struct typedef observation is a great one, it makes sense to me. 
Just to confirm, are you saying that if the structure was to be defined as:
```
typedef struct MTLSize {
    NSUInteger width, height, depth;
} MTLSize;
```
Then I would still need to explicitly provide the encoding for it in my program (it won't be automatically inferred), however, it would be '{_MTLSize=QQQ}' in that case, right?

What If we were able to hint that `device` (from `device.maxThreadsPerThreadgroup`)  conforms to the `MTLDevice` protocol. Won't that do the trick for us? since return type of `maxThreadsPerThreadgroup` is stated right there! 

Obviously, as you and mentioned and @freakboy3742 earlier on, I won't be able to use the '{?=QQQ}' encoding for MTLSize since it will be in conflict with MTLOrigin, which by the way has different field names too. The combination of MTLSize/MTLOrigin/MTLRegion in the source code is actually were I started initially, then I narrowed down my test case to use MTLSize only so I can make my test case reproducer as encapsulated as it might be.

**Comment by dgelessus** [comment] 2019-10-22 10:41
> @dgelessus The anonymous struct typedef observation is a great one, it makes sense to me.
> Just to confirm, are you saying that if the structure was to be defined as:
> 
> ```
> typedef struct MTLSize {
>     NSUInteger width, height, depth;
> } MTLSize;
> ```
> 
> Then I would still need to explicitly provide the encoding for it in my program (it won't be automatically inferred), however, it would be '{_MTLSize=QQQ}' in that case, right?

Almost - the encoding would be `{MTLSize=QQQ}`. The underscore at the start is not added automatically, it's just a convention in some Apple headers. For example, `NSRange` is defined as `typedef struct _NSRange {...} NSRange;`, i. e. `NSRange` is the same as `struct _NSRange`, so its encoding is `{_NSRange=QQ}`.

> What If we were able to hint that `device` (from `device.maxThreadsPerThreadgroup`) conforms to the `MTLDevice` protocol. Won't that do the trick for us? since return type of `maxThreadsPerThreadgroup` is stated right there!

The protocol is not the issue here - the Objective-C runtime already knows the type of `maxThreadsPerThreadgroup`. The problem is that at runtime, all types are represented through their encodings, so `MTLSize` always looks like `{?=QQQ}`. At runtime, there is no way to get any more information than the type encodings, so it's impossible to tell apart `MTLSize` (with encoding `{?=QQQ}`) and `MTLOrigin` (with the same encoding `{?=QQQ}`).

**Comment by freakboy3742** [comment] 2020-04-25 06:57
I believe the original question has been answered; closing on that basis.

**Closed by freakboy3742** 2020-04-25 06:57 UTC
Labels: question
